### ISSUE TITLE
.NET framework

### ISSUE THREAD

**Issue by izabelafs** [SBCNY/Molecular-Biology-of-the-Cell#1]
First of all, thank you for the development! I'm currently in search of a way to classify cell DEG regarding function and your tool seems to be ideal.

However, I'm encountering some setbacks when I try to run in a Ubuntu OS. It requires a .NET framework 4.0 which is not supported anymore and therefore and cannot compile. I'm not a regular user of C# or VS and I'm not sure if would be feasible to migrate the MBCO to a newer framework version. Is it possible or there is any other way to circumvent this issue?

Best,

Izabela

**Comment by JensHansen1** [comment]
Hi Izabela,

thank you very much for your interest in our ontology. Unfortunately, I am not familiar with running C# on other platforms than windows, so I cannot answer your question. The newly uploaded Windows Application (that contains the MBCO v1.1 datasets) also depends on the Windows platform and does not run in an Ubuntu OS. If you want to run the C# script from a newer NET framework, I would just try it. I think it should work. 

Thanks,

Jens
